/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./components/common/ActionMessage.vue')['default']
    ActionSection: typeof import('./components/common/ActionSection.vue')['default']
    ApplicationLogo: typeof import('./components/common/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./components/common/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./components/common/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./components/common/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./components/common/Banner.vue')['default']
    Checkbox: typeof import('./components/common/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./components/common/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./components/common/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./components/common/DangerButton.vue')['default']
    Dashboard: typeof import('./components/dashboard/Dashboard.vue')['default']
    DashboardHeader: typeof import('./components/dashboard/DashboardHeader.vue')['default']
    DialogModal: typeof import('./components/common/DialogModal.vue')['default']
    Dropdown: typeof import('./components/common/Dropdown.vue')['default']
    DropdownLink: typeof import('./components/common/DropdownLink.vue')['default']
    FooterComponent: typeof import('./components/dashboard/FooterComponent.vue')['default']
    FormSection: typeof import('./components/common/FormSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputError: typeof import('./components/common/InputError.vue')['default']
    InputLabel: typeof import('./components/common/InputLabel.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    NavComponent: typeof import('./components/dashboard/NavComponent.vue')['default']
    NavigationItem: typeof import('./components/dashboard/NavigationItem.vue')['default']
    NavLink: typeof import('./components/common/NavLink.vue')['default']
    PrimaryButton: typeof import('./components/common/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./components/common/ResponsiveNavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./components/common/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./components/common/SectionBorder.vue')['default']
    SectionTitle: typeof import('./components/common/SectionTitle.vue')['default']
    Sidebar: typeof import('./components/dashboard/Sidebar.vue')['default']
    TextInput: typeof import('./components/common/TextInput.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
